; Comments start with a single semicolon

; An ABNF rule can contain multiple sub-rules
rule = subrule1 subrule2 subrule3

; We can also use optional angle brackets around a rule name
<oh-look-ma-angle-brackets> = "[]"; We can use double quotes to specify a
                                  ; sequence of characters

; We can specify character directly by using their ASCII/Unicode value
CR = %d13
CR = %x0D
space = %b100000

; -- Invalid Rules -------------------------------------------------------------

<missing-angle-bracket  = "Missing `>`"
illegal$characters_     = "Rule names can only contains certain characters"
