<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>abnf</string>
	</array>
	<key>keyEquivalent</key>
	<string>^~A</string>
	<key>name</key>
	<string>ABNF</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comment</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#rule</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comment</key>
		<dict>
			<key>begin</key>
			<string>(?:(?&lt;leading-whitespace&gt;^[ \t]*)|[ \t]*)(?=;\p{Print}*$)</string>
			<key>beginCaptures</key>
			<dict>
				<key>leading-whitespace</key>
				<dict>
					<key>name</key>
					<string>punctuation.whitespace.comment.leading.abnf</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?!\G)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment-line</string>
				</dict>
			</array>
		</dict>
		<key>comment-line</key>
		<dict>
			<key>begin</key>
			<string>;</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.abnf</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>A line comment starts with a `;` sign and continues to the 
                 end of the line.</string>
			<key>end</key>
			<string>\n</string>
			<key>name</key>
			<string>comment.line.semicolon.abnf</string>
		</dict>
		<key>constant</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#constant-decimal</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#constant-hex</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#constant-binary</string>
				</dict>
			</array>
		</dict>
		<key>constant-binary</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>dash</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.range.abnf</string>
				</dict>
				<key>last</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#digit-binary</string>
						</dict>
					</array>
				</dict>
				<key>number</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#digit-binary</string>
						</dict>
					</array>
				</dict>
				<key>numbers-concat</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#digits-binary-concatenation</string>
						</dict>
					</array>
				</dict>
			</dict>
			<key>match</key>
			<string>(?x)%b
                # First number
                (?&lt;number&gt;[^\s.-]+)        
                # Optional 
                #   - dash followed by last number of range, or
                #   - sequence of additional numbers separated by dot
                (?:(?:(?=-)(?&lt;dash&gt;-)(?&lt;last&gt;\S+)) |
                   (?&lt;numbers-concat&gt;\S+))?</string>
			<key>name</key>
			<string>constant.numeric.binary.abnf</string>
		</dict>
		<key>constant-decimal</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>dash</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.range.abnf</string>
				</dict>
				<key>last</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#digit-decimal</string>
						</dict>
					</array>
				</dict>
				<key>number</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#digit-decimal</string>
						</dict>
					</array>
				</dict>
				<key>numbers-concat</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#digits-decimal-concatenation</string>
						</dict>
					</array>
				</dict>
			</dict>
			<key>match</key>
			<string>(?x)%d
                (?&lt;number&gt;[^\s.-]+)
                (?:(?:(?=-)(?&lt;dash&gt;-)(?&lt;last&gt;\S+)) |
                   (?&lt;numbers-concat&gt;\S+))?</string>
			<key>name</key>
			<string>constant.numeric.decimal.abnf</string>
		</dict>
		<key>constant-hex</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>dash</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.range.abnf</string>
				</dict>
				<key>last</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#digit-hex</string>
						</dict>
					</array>
				</dict>
				<key>number</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#digit-hex</string>
						</dict>
					</array>
				</dict>
				<key>numbers-concat</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#digits-hex-concatenation</string>
						</dict>
					</array>
				</dict>
			</dict>
			<key>match</key>
			<string>(?x)%x
                (?&lt;number&gt;[^\s.-]+)
                (?:(?:(?=-)(?&lt;dash&gt;-)(?&lt;last&gt;\S+)) |
                   (?&lt;numbers-concat&gt;\S+))?</string>
			<key>name</key>
			<string>constant.numeric.hex.abnf</string>
		</dict>
		<key>digit-binary</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#digit-binary-valid</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#digit-binary-invalid</string>
				</dict>
			</array>
		</dict>
		<key>digit-binary-invalid</key>
		<dict>
			<key>match</key>
			<string>\S</string>
			<key>name</key>
			<string>invalid.illegal.digit.binary.abnf</string>
		</dict>
		<key>digit-binary-valid</key>
		<dict>
			<key>match</key>
			<string>[01]</string>
		</dict>
		<key>digit-decimal</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#digit-decimal-valid</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#digit-decimal-invalid</string>
				</dict>
			</array>
		</dict>
		<key>digit-decimal-invalid</key>
		<dict>
			<key>match</key>
			<string>\S</string>
			<key>name</key>
			<string>invalid.illegal.digit.decimal.abnf</string>
		</dict>
		<key>digit-decimal-valid</key>
		<dict>
			<key>match</key>
			<string>\d</string>
		</dict>
		<key>digit-hex</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#digit-hex-valid</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#digit-hex-invalid</string>
				</dict>
			</array>
		</dict>
		<key>digit-hex-invalid</key>
		<dict>
			<key>match</key>
			<string>\S</string>
			<key>name</key>
			<string>invalid.illegal.digit.hex.abnf</string>
		</dict>
		<key>digit-hex-valid</key>
		<dict>
			<key>match</key>
			<string>\h</string>
		</dict>
		<key>digits-binary-concatenation</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>dot</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.concatenation.abnf</string>
				</dict>
				<key>number</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#digit-binary</string>
						</dict>
					</array>
				</dict>
			</dict>
			<key>match</key>
			<string>(?&lt;dot&gt;\.)(?&lt;number&gt;[^\s.]+)</string>
		</dict>
		<key>digits-decimal-concatenation</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>dot</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.concatenation.abnf</string>
				</dict>
				<key>number</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#digit-decimal</string>
						</dict>
					</array>
				</dict>
			</dict>
			<key>match</key>
			<string>(?&lt;dot&gt;\.)(?&lt;number&gt;[^\s.]+)</string>
		</dict>
		<key>digits-hex-concatenation</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>dot</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.concatenation.abnf</string>
				</dict>
				<key>number</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#digit-hex</string>
						</dict>
					</array>
				</dict>
			</dict>
			<key>match</key>
			<string>(?&lt;dot&gt;\.)(?&lt;number&gt;[^\s.]+)</string>
		</dict>
		<key>operator</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#operator-equal</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#operator-equal-alternative</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#operator-alternative</string>
				</dict>
			</array>
		</dict>
		<key>operator-alternative</key>
		<dict>
			<key>match</key>
			<string>/</string>
			<key>name</key>
			<string>keyword.operator.alternative.abnf</string>
		</dict>
		<key>operator-equal</key>
		<dict>
			<key>match</key>
			<string>=(?!/)</string>
			<key>name</key>
			<string>keyword.operator.equal.abnf</string>
		</dict>
		<key>operator-equal-alternative</key>
		<dict>
			<key>match</key>
			<string>=/</string>
			<key>name</key>
			<string>keyword.operator.equal-alternative.abnf</string>
		</dict>
		<key>rule</key>
		<dict>
			<key>begin</key>
			<string>(?x)^(\s*)
                 # We match the name of the rule and all following whitespace 
                 # characters. We use the additional whitespace to catch a 
                 # missing closing angle bracket.
                 (?&lt;name&gt;\S+\s+)</string>
			<key>captures</key>
			<dict>
				<key>name</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#rule-name-angle-brackets</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#rule-name</string>
						</dict>
					</array>
				</dict>
			</dict>
			<key>comment</key>
			<string>A rule start with a possibly empty sequence of whitespace. The 
                 rule continues if the next line starts with at least one more
                 whitespace character than the initial line of the rule.</string>
			<key>name</key>
			<string>meta.rule.abnf</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#rule-right-side</string>
				</dict>
			</array>
			<key>while</key>
			<string>^(?=\1\s)</string>
		</dict>
		<key>rule-group</key>
		<dict>
			<key>begin</key>
			<string>\(</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.group.abnf</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\)</string>
			<key>name</key>
			<string>meta.rule.group.abnf</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#rule-right-side</string>
				</dict>
			</array>
		</dict>
		<key>rule-name</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>invalid</key>
				<dict>
					<key>name</key>
					<string>invalid.illegal.character.abnf</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>The name of a rule is a sequence of characters, beginning 
                 with an alphabetic character, and followed by a combination of 
                 alphabetic characters, digits, and hyphens (dashes)</string>
			<key>match</key>
			<string>[a-zA-Z][a-zA-Z0-9\-]*|(?&lt;invalid&gt;\S)</string>
			<key>name</key>
			<string>variable.other.rule.abnf</string>
		</dict>
		<key>rule-name-angle-brackets</key>
		<dict>
			<key>begin</key>
			<string>&lt;</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.other.angle-bracket.abnf</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Angle brackets may be used around a rule name.</string>
			<key>end</key>
			<string>&gt;|(\s)</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.other.angle-bracket.abnf</string>
				</dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>invalid.illegal.missing.angle-bracket.abnf</string>
				</dict>
			</dict>
			<key>name</key>
			<string>variable.other.rule</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#rule-name</string>
				</dict>
			</array>
		</dict>
		<key>rule-right-side</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#rule-group</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#operator</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#constant</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string-double-quoted</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#rule-name</string>
				</dict>
			</array>
		</dict>
		<key>string-double-quoted</key>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.abnf</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.abnf</string>
	<key>uuid</key>
	<string>7E104F42-A7B3-47CE-AE6E-D55E62C4D5E0</string>
</dict>
</plist>
